Controllers/AnunciosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using aluguel.Areas.Identity.Data;
using aluguel.Models;
using System.Security.Claims;

namespace aluguel.Controllers
{
    public class AnunciosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AnunciosController(ApplicationDbContext context)
        {
            _context = context;
        }

        //var applicationDbContext = _context.Anuncios.Include(a => a.item);
        //    return View(await applicationDbContext.ToListAsync());



        // GET: Anuncios
        public async Task<IActionResult> Index()
        {
            var model = await _context.Anuncios
                            .Where(a => a.iduser == HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value)
                            .Include(a => a.item)
                            .ToListAsync();
            return View(model);

        }

        // GET: Anuncios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Anuncios == null)
            {
                return NotFound();
            }

            var anuncio = await _context.Anuncios
                .Include(a => a.item)
                .FirstOrDefaultAsync(m => m.id == id);
            if (anuncio == null)
            {
                return NotFound();
            }

            return View(anuncio);
        }

        // GET: Anuncios/Create
        public IActionResult Create()
        {
            
            ViewData["itemid"] = new SelectList(_context.Items
                .Where(a => a.iduser == HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value && a.snativo != "N"), "id", "nmitem");
                
                return View();
        }

        // POST: Anuncios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,vlitem,diasAluguel,iduser,itemid,estado,cidade,bairro,contato")] Anuncio anuncio)
        {
            if (ModelState.IsValid)
            {
                _context.Add(anuncio);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["itemid"] = new SelectList(_context.Items, "id", "id", anuncio.itemid);
            return View(anuncio);
        }

        // GET: Anuncios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Anuncios == null)
            {
                return NotFound();
            }

            var anuncio = await _context.Anuncios.FindAsync(id);
            if (anuncio == null)
            {
                return NotFound();
            }
            ViewData["itemid"] = new SelectList(_context.Items, "id", "id", anuncio.itemid);
            return View(anuncio);
        }

        // POST: Anuncios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,vlitem,diasAluguel,iduser,itemid,estado,cidade,bairro,contato")] Anuncio anuncio)
        {
            if (id != anuncio.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(anuncio);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AnuncioExists(anuncio.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["itemid"] = new SelectList(_context.Items, "id", "id", anuncio.itemid);
            return View(anuncio);
        }

        // GET: Anuncios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Anuncios == null)
            {
                return NotFound();
            }

            var anuncio = await _context.Anuncios
                .Include(a => a.item)
                .FirstOrDefaultAsync(m => m.id == id);
            if (anuncio == null)
            {
                return NotFound();
            }

            return View(anuncio);
        }

        // POST: Anuncios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Anuncios == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Anuncios'  is null.");
            }
            var anuncio = await _context.Anuncios.FindAsync(id);
            if (anuncio != null)
            {
                _context.Anuncios.Remove(anuncio);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AnuncioExists(int id)
        {
            return (_context.Anuncios?.Any(e => e.id == id)).GetValueOrDefault();
        }
    }
}

Controllers/ItemsController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Net;
using aluguel.Models;
using aluguel.ViewModel;
using aluguel.Areas.Identity.Data;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore;
using SendGrid.Helpers.Mail;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace aluguel.Controllers
{
    public class ItemsController : Controller
    {
        private readonly ILogger<ItemsController> _logger;
        private readonly ApplicationDbContext Context;
        private readonly IWebHostEnvironment WebHostEnvironment;

        public ItemsController(ILogger<ItemsController> logger, ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _logger = logger;
            Context = context;
            WebHostEnvironment = webHostEnvironment;
        }

        public async Task<IActionResult> Index()
        {
            var model = await Context.Items
                            .Where(a => a.iduser == HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value)
                            .ToListAsync();
            return View(model);

        }

        // GET: Items/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || Context.Items == null)
            {
                return NotFound();
            }

            var item = await Context.Items
                .FirstOrDefaultAsync(m => m.id == id);
            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(ItemViewModel vm)
        {
            string stringFileName = UploadFile(vm);
            var item = new Item
            {
                nmitem = vm.nmitem,
                dsitem = vm.dsitem,
                dtcriacao = vm.dtcriacao = DateTime.Now,
                snativo = vm.snativo,
                iduser = vm.iduser,
                imagem = stringFileName

            };
            Context.Items.Add(item);
            Context.SaveChanges();

            return RedirectToAction("Index");
        }

        // GET: Items/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || Context.Items == null)
            {
                return NotFound();
            }

            var item = await Context.Items.FindAsync(id);
            if (item == null)
            {
                return NotFound();
            }
            return View(item);
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,nmitem,dsitem,dtcriacao,snativo,imagem,iduser")] Item item)
        {
            if (id != item.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Context.Update(item);
                    await Context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ItemExists(item.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(item);
        }

        // GET: Items/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || Context.Items == null)
            {
                return NotFound();
            }

            var item = await Context.Items
                .FirstOrDefaultAsync(m => m.id == id);
            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (Context.Items == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Items'  is null.");
            }
            var item = await Context.Items.FindAsync(id);
            if (item != null)
            {
                Context.Items.Remove(item);
            }
            
            await Context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private string UploadFile(ItemViewModel vm)
        {
            string fileName = null;
            if (vm.imagem != null)
            {
                string uploadDir = Path.Combine(WebHostEnvironment.WebRootPath, "imagens");
                fileName = Guid.NewGuid().ToString() + "-" + vm.imagem.FileName;
                string filePath = Path.Combine(uploadDir, fileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    vm.imagem.CopyTo(fileStream);
                }
            }
            return fileName;
        }

        private bool ItemExists(int id)
        {
          return (Context.Items?.Any(e => e.id == id)).GetValueOrDefault();
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using aluguel.Areas.Identity.Data

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <link rel="shortcut icon" href="/imagens/ico.ico" type="image/x-icon" />
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>RentAll</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/cadastro.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/voltartopo.css" asp-append-version="true" />
    <script src="https://kit.fontawesome.com/f9a4013b2c.js" crossorigin="anonymous"></script>

</head>
<body>

    <div vw class="enabled">
        <div vw-access-button class="active"></div>
        <div vw-plugin-wrapper>
            <div class="vw-plugin-top-wrapper"></div>
        </div>
       
    </div>
    <script src="https://vlibras.gov.br/app/vlibras-plugin.js"></script>
    <script>
        new window.VLibras.Widget('https://vlibras.gov.br/app');
    </script>



    <header>
        
        <nav>
            <a class="logo" href="/">Rent All</a>
            <div class="mobile-menu">
                <div class="line1"></div>
                <div class="line2"></div>
                <div class="line3"></div>
            </div>
            <ul class="nav-list">
                
                <li class="nav">
                    <a class="nav-link text-white-50" asp-area="" asp-controller="Home" asp-action="Index">Menu Principal</a>
                </li>
                <li class="nav">
                    <a class="nav-link text-white-50" asp-area="" asp-controller="Home" asp-action="Privacy">Sobre nós</a>
                </li>
                @if (User.Identity.IsAuthenticated)
                {}
                else
                {
                <li class="nav-item">
                    <a class="nav-link text-dark" id="login" asp-area="Identity" asp-page="/Account/Login">Entrar</a>
                </li>    
                }
                @if (SignInManager.IsSignedIn(User))
                {
                    <li class="nav">
                        <a class="nav-link text-white-50" asp-area="" asp-controller="Items" asp-action="Index">Itens</a>
                    </li>
                    <li class="nav">
                        <a class="nav-link text-white-50" asp-area="" asp-controller="Anuncios" asp-action="Index">Anúncios</a>
                    </li>
                    <li class="nav-item">
                        <a id="manage" class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Olá @User.GetFirstName()!</a>
                    </li>
                    <li class="nav-item">
                        <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                            <button type="submit">Sair</button>
                        </form>
                    </li>
                }
            </ul>
        </nav>
    </header>

    <div class="container">

        <main role="main" class="pb-3">
            @RenderBody()
        </main>

    </div>
    <script type="text/javascript" src="~/js/cadastro.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/mobile-navbar.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>